# Generated by Django 3.0.3 on 2020-02-07 11:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourslot',
            name='legal_duration',
            field=models.DurationField(default=django.utils.timezone.now() - django.utils.timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.School')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.SchoolYear')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.School')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.SchoolYear')),
            ],
        ),
        migrations.CreateModel(
            name='HoursPerTeacherInClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField()),
                ('hours_bes', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.School')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.SchoolYear')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=256)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.School')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.SchoolYear')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour_start', models.TimeField()),
                ('hour_end', models.TimeField()),
                ('bes', models.BooleanField(default=False)),
                ('substitution', models.BooleanField(default=False)),
                ('absent', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.School')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.SchoolYear')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='AbsenceBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.HourSlot')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.SchoolYear')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Teacher')),
            ],
        ),
    ]
