# Generated by Django 3.0.3 on 2020-02-08 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20200208_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='date',
            new_name='date_end',
        ),
        migrations.AddField(
            model_name='holiday',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
