# Generated by Django 3.0.3 on 2020-06-23 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_stage_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminschool',
            options={'verbose_name': 'Admin School'},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='school_year',
        ),
        migrations.AlterField(
            model_name='absenceblock',
            name='hour_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.HourSlot', verbose_name='hour slot'),
        ),
        migrations.AlterField(
            model_name='absenceblock',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.SchoolYear', verbose_name='school year'),
        ),
        migrations.AlterField(
            model_name='absenceblock',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Teacher', verbose_name='teacher'),
        ),
        migrations.AlterField(
            model_name='adminschool',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.School', verbose_name='school'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='absent',
            field=models.BooleanField(default=False, verbose_name='absence'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='bes',
            field=models.BooleanField(default=False, verbose_name='BES'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Course', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='hour_end',
            field=models.TimeField(verbose_name='end hour'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='hour_start',
            field=models.TimeField(verbose_name='start hour'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.School', verbose_name='school'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.SchoolYear', verbose_name='school year'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Subject', verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='substitution',
            field=models.BooleanField(default=False, verbose_name='substitution'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Teacher', verbose_name='teacher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.School', verbose_name='school'),
        ),
        migrations.AlterField(
            model_name='course',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.SchoolYear', verbose_name='school year'),
        ),
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.CharField(max_length=256, verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date_end',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date_start',
            field=models.DateField(verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.School', verbose_name='school'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.SchoolYear', verbose_name='school year'),
        ),
        migrations.AlterField(
            model_name='hourslot',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='day of the week'),
        ),
        migrations.AlterField(
            model_name='hourslot',
            name='ends_at',
            field=models.TimeField(verbose_name='ends at'),
        ),
        migrations.AlterField(
            model_name='hourslot',
            name='hour_number',
            field=models.IntegerField(verbose_name='hour number'),
        ),
        migrations.AlterField(
            model_name='hourslot',
            name='legal_duration',
            field=models.DurationField(verbose_name='legal duration'),
        ),
        migrations.AlterField(
            model_name='hourslot',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.School', verbose_name='school'),
        ),
        migrations.AlterField(
            model_name='hourslot',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.SchoolYear', verbose_name='school year'),
        ),
        migrations.AlterField(
            model_name='hourslot',
            name='starts_at',
            field=models.TimeField(verbose_name='begins at'),
        ),
        migrations.AlterField(
            model_name='hoursperteacherinclass',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Course', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='hoursperteacherinclass',
            name='hours',
            field=models.IntegerField(verbose_name='hours'),
        ),
        migrations.AlterField(
            model_name='hoursperteacherinclass',
            name='hours_bes',
            field=models.IntegerField(verbose_name='hours BES'),
        ),
        migrations.AlterField(
            model_name='hoursperteacherinclass',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.School', verbose_name='school'),
        ),
        migrations.AlterField(
            model_name='hoursperteacherinclass',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.SchoolYear', verbose_name='school year'),
        ),
        migrations.AlterField(
            model_name='hoursperteacherinclass',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Subject', verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='hoursperteacherinclass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Teacher', verbose_name='teacher'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='date_start',
            field=models.DateField(verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='year_start',
            field=models.IntegerField(verbose_name='start year'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Course', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='date_end',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='date_start',
            field=models.DateField(verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.School', verbose_name='school'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.SchoolYear', verbose_name='school year'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.School', verbose_name='school'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.School', verbose_name='school'),
        ),
    ]
