# Generated by Django 3.0.3 on 2020-07-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_auto_20200626_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='free_substitution',
            field=models.BooleanField(default=False, verbose_name='free_substitution'),
        ),
    ]
