# Generated by Django 3.0.8 on 2020-07-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_assignment_free_substitution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absenceblock',
            name='school_year',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='free_substitution',
            field=models.BooleanField(default=False, verbose_name='free substitution'),
        ),
    ]
