# Generated by Django 3.0.8 on 2020-07-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_auto_20200713_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='school_year',
        ),
    ]
