# Generated by Django 3.0.8 on 2020-07-13 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_remove_stage_school_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoursperteacherinclass',
            name='school_year',
        ),
    ]
