# Generated by Django 3.0.8 on 2020-07-13 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_remove_hoursperteacherinclass_school_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='school_year',
        ),
    ]
