# Generated by Django 3.0.8 on 2020-07-15 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_remove_assignment_school_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersYearlyLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearly_load', models.IntegerField(verbose_name='yearly load')),
                ('yearly_load_bes', models.IntegerField(verbose_name='yearly load bes')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.SchoolYear', verbose_name='school year')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Teacher', verbose_name='teacher')),
            ],
        ),
    ]
