# Generated by Django 3.0.8 on 2020-07-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0015_coursesyearlyload'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoursperteacherinclass',
            name='hours_co_teaching',
            field=models.IntegerField(default=0, verbose_name='Hours co-teaching'),
        ),
    ]
