# Generated by Django 3.0.8 on 2020-07-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0016_hoursperteacherinclass_hours_co_teaching'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='co_teaching',
            field=models.BooleanField(default=False, verbose_name='Co-teaching'),
        ),
    ]
