# Generated by Django 3.0.8 on 2020-07-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0017_assignment_co_teaching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoursperteacherinclass',
            name='hours_co_teaching',
            field=models.IntegerField(verbose_name='Hours co-teaching'),
        ),
    ]
