# Generated by Django 3.0.8 on 2020-07-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0019_teachersyearlyload_yearly_load_co_teaching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersyearlyload',
            name='yearly_load_co_teaching',
            field=models.IntegerField(verbose_name='yearly load co-teaching'),
        ),
    ]
