# Generated by Django 3.0.8 on 2020-09-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0025_auto_20200907_1819'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('year', 'section', 'hour_slots_group')},
        ),
    ]
