# Generated by Django 3.0.8 on 2020-09-12 12:20

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0026_auto_20200912_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color',
            field=colorfield.fields.ColorField(default='#20B2AA', max_length=18, verbose_name='color'),
        ),
    ]
