# Generated by Django 3.0.8 on 2021-01-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0027_subject_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='in_activity',
            field=models.BooleanField(default=True, verbose_name='in activity'),
        ),
    ]
