# Generated by Django 3.0.8 on 2021-02-04 10:52

from django.db import migrations, models
import django.db.models.deletion


def find_substituted_assignment(apps, schema_editor):
    """
    For every substitution assignment, find the substituted assignment and link it to the
    substitution using the foreign key substituted_assignment.
    """
    db_alias = schema_editor.connection.alias
    Assignment = apps.get_model("timetable", "Assignment")

    for assign in Assignment.objects.filter(substitution=True):
        # For every substitution, pick the substituted assignment and link it using the new FK.
        ass_substituted = Assignment.objects.filter(
            course=assign.course,
            subject=assign.subject,
            date=assign.date,
            hour_start=assign.hour_start,
            hour_end=assign.hour_end,
            bes=assign.bes,
            co_teaching=assign.co_teaching,
            absent=True,
        ).first()     # If there are multiple candidates, pick the first (May be improved).
        assign.substituted_assignment = ass_substituted
        assign.save()


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0028_teacher_in_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='substituted_assignment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.Assignment', verbose_name='substituted assignment'),
        ),
        migrations.RunPython(find_substituted_assignment)
    ]
