# Generated by Django 3.0.3 on 2020-02-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0005_auto_20200208_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
